export const SECTOR_LABELS: Record<string, string> = {
  "fashion": "Fashion",
  "handicrafts": "Handicrafts",
  "food-processing": "Food Processing",
  "tourism-hospitality": "Tourism & Hospitality",
  "textiles": "Textiles",
  "technology-it": "Technology & IT",
  "agriculture-horticulture": "Agriculture & Horticulture",
  "others": "Others",
};

export const DISTRICT_LABELS: Record<string, string> = {
  "east-khasi-hills": "East Khasi Hills",
  "west-khasi-hills": "West Khasi Hills",
  "eastern-west-khasi-hills": "Eastern West Khasi Hills",
  "south-west-khasi-hills": "South West Khasi Hills",
  "ri-bhoi": "Ri Bhoi",
  "east-jaintia-hills": "East Jaintia Hills",
  "west-jaintia-hills": "West Jaintia Hills",
  "east-garo-hills": "East Garo Hills",
  "west-garo-hills": "West Garo Hills",
  "south-garo-hills": "South Garo Hills",
  "north-garo-hills": "North Garo Hills",
};

export type EntrepreneurProfile = {
  slug: string;
  businessName: string;
  entrepreneurName: string;
  district: string;
  sector: string;
  image: string;
  // Optional detailed fields
  description?: string;
  location?: string;
  email?: string;
  phone?: string;
  entity?: string;
  stage?: string;
  employment?: string;
  livesImpacted?: string;
  turnover?: string;
  govtFunding?: string;
  externalFunding?: string;
  socialImpact?: string;
  products?: string;
  externalLink: string;
};

export const profiles: EntrepreneurProfile[] = [
  {
    slug: "mohor",
    businessName: "Mohor",
    entrepreneurName: "Cordelia Kharsati",
    district: "east-khasi-hills",
    sector: "fashion",
    image: "Custommahor2.jpg",
    externalLink: "https://www.primemeghalaya.com/mohor/",
  },
  {
    slug: "btm-arts",
    businessName: "BTM Arts",
    entrepreneurName: "Bashanbok Myrboh",
    district: "east-khasi-hills",
    sector: "handicrafts",
    image: "btmarts.jpg",
    externalLink: "https://www.primemeghalaya.com/btm-arts/",
  },
  {
    slug: "zero9-farms",
    businessName: "Zero9 Farms",
    entrepreneurName: "Bitchri Sekso Mebitchi R Marak, Damuda D Sangma",
    district: "south-garo-hills",
    sector: "food-processing",
    image: "Zero9Farms.jpg",
    description: "Bitchri Sekso Mebitchi R Marak founded Zero9 Farms, a food processing unit aimed at harnessing the richness of Meghalaya's resources to create high-quality products that cater to both the needs and desires of people.",
    location: "Balsrigittim, Baghmara, South Garo Hills District",
    email: "seksomarak12@gmail.com",
    phone: "8787326383",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "5",
    livesImpacted: "20",
    turnover: "₹5 Lakh",
    govtFunding: "₹2 Lakh",
    externalFunding: "N/A",
    socialImpact: "Zero9 Farms supports local agriculture by sourcing ingredients from Meghalaya's rich natural resources. Through food processing, the company creates sustainable income opportunities for farmers and artisans. By producing high-quality products, Zero9 Farms contributes to the local economy while promoting the region's agricultural heritage.",
    products: "Jujube candy, Tamarind candy, Shredded meat & Pickle, Oyster Mushroom Pickle, Seasonal fruit wine, Marmalade, Passion Fruit & Pineapple Jam, Strawberry Jam",
    externalLink: "https://www.primemeghalaya.com/zero9-farms/",
  },
  {
    slug: "shangkai",
    businessName: "Shangkai",
    entrepreneurName: "Damanbha Khongstia",
    district: "east-khasi-hills",
    sector: "tourism-hospitality",
    image: "Shangkai4.jpg",
    externalLink: "https://www.primemeghalaya.com/shangkai/",
  },
  {
    slug: "four-o-four",
    businessName: "Four O Four",
    entrepreneurName: "Eveleen E Marbaniang",
    district: "east-khasi-hills",
    sector: "handicrafts",
    image: "FourOFourProfile.jpg",
    externalLink: "https://www.primemeghalaya.com/four-o-four",
  },
  {
    slug: "laichaphrang-handicraft",
    businessName: "Laichaphrang Handicraft",
    entrepreneurName: "Jenifer Suiam",
    district: "west-jaintia-hills",
    sector: "handicrafts",
    image: "Laichphrangprofile.jpg",
    externalLink: "https://www.primemeghalaya.com/laichaphrang-handicraft",
  },
  {
    slug: "hcollection",
    businessName: "Hcollection",
    entrepreneurName: "Hilarious Kharlyngdoh",
    district: "east-khasi-hills",
    sector: "fashion",
    image: "Hcollectionproduct.jpg",
    externalLink: "https://www.primemeghalaya.com/hcollection/",
  },
  {
    slug: "jets-24x7",
    businessName: "JETS 24x7",
    entrepreneurName: "Pynskhemlang W Uriah",
    district: "east-khasi-hills",
    sector: "others",
    image: "jets2.jpg",
    externalLink: "https://www.primemeghalaya.com/jets-24x7/",
  },
  {
    slug: "machine-khoh-kwai",
    businessName: "Machine khoh kwai",
    entrepreneurName: "Wanlang Lakuna",
    district: "east-khasi-hills",
    sector: "others",
    image: "Machinekhohkwaiimage.jpg",
    externalLink: "https://www.primemeghalaya.com/machine-khoh-kwai/",
  },
  {
    slug: "zong-hi-i",
    businessName: "Zong Hi I",
    entrepreneurName: "Precious Star Tmung",
    district: "ri-bhoi",
    sector: "textiles",
    image: "zonghii.jpg",
    externalLink: "https://www.primemeghalaya.com/zong-hi-i",
  },
  {
    slug: "surwandiam-enterprise-av-production",
    businessName: "Surwandiam Enterprise AV Production",
    entrepreneurName: "Pondermost Khongkliam",
    district: "east-khasi-hills",
    sector: "others",
    image: "SurwandiamEnterprise3.jpg",
    externalLink: "https://www.primemeghalaya.com/surwandiam-enterprise-av-production",
  },
  {
    slug: "ceefle-venture",
    businessName: "Ceefle Venture",
    entrepreneurName: "Babitdor Kharsohtun",
    district: "east-khasi-hills",
    sector: "food-processing",
    image: "ceefleprofile.jpg",
    externalLink: "https://www.primemeghalaya.com/ceefle-venture",
  },
  {
    slug: "crochet-haven",
    businessName: "Crochet Haven",
    entrepreneurName: "Ibajanai Lyngdoh",
    district: "east-khasi-hills",
    sector: "handicrafts",
    image: "CrochetHavenprofile.jpg",
    externalLink: "https://www.primemeghalaya.com/crochet-haven",
  },
  {
    slug: "rose-tegite",
    businessName: "Rose Tegite",
    entrepreneurName: "Rosemary T Sangma",
    district: "south-garo-hills",
    sector: "fashion",
    image: "RoseTegiteprofile.jpg",
    externalLink: "https://www.primemeghalaya.com/rose-tegite",
  },
  {
    slug: "salgro-wood-carving",
    businessName: "Salgro Wood-Carving",
    entrepreneurName: "Thengku Sangma",
    district: "north-garo-hills",
    sector: "handicrafts",
    image: "SalgroWoodCarvingimg.jpg",
    externalLink: "https://www.primemeghalaya.com/salgro-wood-carving",
  },
  {
    slug: "medira-handloom",
    businessName: "Medira handloom",
    entrepreneurName: "Medira G Sangma",
    district: "west-garo-hills",
    sector: "textiles",
    image: "Medirahandloomprofile.jpg",
    externalLink: "https://www.primemeghalaya.com/medira-handloom",
  },
  {
    slug: "cassey-turima",
    businessName: "Cassey Turima",
    entrepreneurName: "Cassey Turima M Marak",
    district: "west-garo-hills",
    sector: "handicrafts",
    image: "CasseyTurima1.jpg",
    externalLink: "https://www.primemeghalaya.com/cassey-turima",
  },
  {
    slug: "rising-26-9",
    businessName: "Rising 26-9",
    entrepreneurName: "Nichang Momin",
    district: "west-garo-hills",
    sector: "handicrafts",
    image: "Risingcp.jpg",
    externalLink: "https://www.primemeghalaya.com/rising-26-9",
  },
  {
    slug: "wedoa-chocolate",
    businessName: "WEDOA chocolate",
    entrepreneurName: "Tiara Roxettee M Sangma",
    district: "west-garo-hills",
    sector: "food-processing",
    image: "WEDOAcp.jpg",
    externalLink: "https://www.primemeghalaya.com/wedoa-chocolate",
  },
  {
    slug: "shillong-agro-solutions",
    businessName: "Shillong Agro Solutions",
    entrepreneurName: "Wanlambok Wanshuwa Kshiar Shadap",
    district: "east-khasi-hills",
    sector: "food-processing",
    image: "Shillongagrosolutions3.jpg",
    externalLink: "https://www.primemeghalaya.com/shillong-agro-solutions/",
  },
  {
    slug: "ls-food-products",
    businessName: "LS.Food Products",
    entrepreneurName: "Thruslinda S Sangma",
    district: "west-garo-hills",
    sector: "food-processing",
    image: "Lsfoodproductcp.jpg",
    externalLink: "https://www.primemeghalaya.com/ls-food-products/",
  },
  {
    slug: "mei-ramew-cafe-jingbam-tynrai",
    businessName: "Mei-Ramew Cafe",
    entrepreneurName: "Plantina Mujai",
    district: "ri-bhoi",
    sector: "tourism-hospitality",
    image: "Meiramewcafecp.jpg",
    externalLink: "https://www.primemeghalaya.com/mei-ramew-cafe-jingbam-tynrai/",
  },
  {
    slug: "boba-bae",
    businessName: "Boba Bae",
    entrepreneurName: "Lyzander Sohkhlet",
    district: "east-khasi-hills",
    sector: "food-processing",
    image: "Bobabaecp.jpg",
    externalLink: "https://www.primemeghalaya.com/boba-bae/",
  },
  {
    slug: "your-tee-your-style",
    businessName: "Your Tee Your Style",
    entrepreneurName: "Shano Chelsy M Sangma",
    district: "west-garo-hills",
    sector: "others",
    image: "Yourteeyourstylecp.jpg",
    externalLink: "https://www.primemeghalaya.com/your-tee-your-style/",
  },
  {
    slug: "digital-fuel",
    businessName: "Digital Fuel",
    entrepreneurName: "Mansha Sharma",
    district: "east-khasi-hills",
    sector: "technology-it",
    image: "digitalfuelcp.jpg",
    externalLink: "https://www.primemeghalaya.com/digital-fuel/",
  },
  {
    slug: "soola",
    businessName: "Soola",
    entrepreneurName: "Glorisa Kalra War & Wanda Kharakor",
    district: "east-khasi-hills",
    sector: "fashion",
    image: "soolaprofile.jpg",
    externalLink: "https://www.primemeghalaya.com/soola/",
  },
  {
    slug: "solipsis-design",
    businessName: "Solipsis Design",
    entrepreneurName: "Rundolf Mawlieh",
    district: "east-khasi-hills",
    sector: "technology-it",
    image: "solipsiscp.jpg",
    externalLink: "https://www.primemeghalaya.com/solipsis-design",
  },
  {
    slug: "rida-sten-food-cottage",
    businessName: "Rida Sten Food Cottage",
    entrepreneurName: "Niwania I Sten",
    district: "west-jaintia-hills",
    sector: "food-processing",
    image: "Ridastenfoodcottagecp.jpg",
    externalLink: "https://www.primemeghalaya.com/rida-sten-food-cottage",
  },
  {
    slug: "little-sunshine-boutique-and-nursery",
    businessName: "Little SunShine Boutique and Nursery",
    entrepreneurName: "Boblyford Thangkhiew",
    district: "east-khasi-hills",
    sector: "agriculture-horticulture",
    image: "Littlesunshinecp.jpg",
    externalLink: "https://www.primemeghalaya.com/little-sunshine-boutique-and-nursery/",
  },
  {
    slug: "sakhiona",
    businessName: "Sakhiona",
    entrepreneurName: "Sakhihok Lamare",
    district: "west-jaintia-hills",
    sector: "food-processing",
    image: "Sakhionaprofile.jpg",
    externalLink: "https://www.primemeghalaya.com/sakhiona/",
  },
  {
    slug: "bithon-bamboo",
    businessName: "Bithon Bamboo",
    entrepreneurName: "Bithon D Sangma",
    district: "east-garo-hills",
    sector: "handicrafts",
    image: "Bithonbamboocp.jpg",
    externalLink: "https://www.primemeghalaya.com/bithon-bamboo",
  },
  {
    slug: "nengminja-industry",
    businessName: "Nengminja industry",
    entrepreneurName: "Briana Novemchi N. Sangma",
    district: "west-garo-hills",
    sector: "fashion",
    image: "Nengminjaindustrycp.jpg",
    externalLink: "https://www.primemeghalaya.com/nengminja-industry/",
  },
  {
    slug: "level-up-virtual-experience-cafe",
    businessName: "Level Up",
    entrepreneurName: "Yashraj A. Sangma",
    district: "west-garo-hills",
    sector: "technology-it",
    image: "Levelupcp.jpg",
    externalLink: "https://www.primemeghalaya.com/level-up-virtual-experience-cafe/",
  },
  {
    slug: "sj-visual-art",
    businessName: "SJ Visual Art",
    entrepreneurName: "Saljagring N Arengh",
    district: "west-garo-hills",
    sector: "others",
    image: "SJvisualartcp.jpg",
    externalLink: "https://www.primemeghalaya.com/sj-visual-art",
  },
  {
    slug: "houseofura-studio",
    businessName: "houseofura.studio",
    entrepreneurName: "Divya K Marak",
    district: "west-garo-hills",
    sector: "fashion",
    image: "houseofurastudiocp.jpg",
    externalLink: "https://www.primemeghalaya.com/houseofura-studio",
  },
  {
    slug: "the-tea-story",
    businessName: "The Tea Story",
    entrepreneurName: "Bibian Momin",
    district: "west-garo-hills",
    sector: "food-processing",
    image: "Theteastorycp.jpg",
    externalLink: "https://www.primemeghalaya.com/the-tea-story/",
  },
  {
    slug: "durama-handicrafts",
    businessName: "Durama handicrafts",
    entrepreneurName: "Brithing C Marak",
    district: "south-garo-hills",
    sector: "handicrafts",
    image: "Duramahandicrafts2.jpg",
    externalLink: "https://www.primemeghalaya.com/durama-handicrafts",
  },
  {
    slug: "vision-to-arts-and-fashion-design",
    businessName: "Vision To Arts And Fashion Design",
    entrepreneurName: "Larimika Syrti",
    district: "east-jaintia-hills",
    sector: "fashion",
    image: "larimikacp.jpg",
    externalLink: "https://www.primemeghalaya.com/vision-to-arts-and-fashion-design/",
  },
  {
    slug: "m-s-sari-soap",
    businessName: "M/S SARI SOAP",
    entrepreneurName: "Dau Ruhi Sari",
    district: "west-jaintia-hills",
    sector: "others",
    image: "Sarisoapprofilr.jpg",
    externalLink: "https://www.primemeghalaya.com/m-s-sari-soap/",
  },
  {
    slug: "lokki-food-products",
    businessName: "Lokki Food Products",
    entrepreneurName: "Lokki M Sangma",
    district: "east-garo-hills",
    sector: "food-processing",
    image: "lokkifoodproductscp.jpg",
    externalLink: "https://www.primemeghalaya.com/lokki-food-products",
  },
  {
    slug: "oihelp",
    businessName: "OiHelp",
    entrepreneurName: "Avik Chakraborty",
    district: "west-garo-hills",
    sector: "technology-it",
    image: "oihelpcp.jpg",
    externalLink: "https://www.primemeghalaya.com/oihelp",
  },
  {
    slug: "7-united-rice-beer",
    businessName: "7 United Rice Beer",
    entrepreneurName: "Keenan K Marak",
    district: "west-garo-hills",
    sector: "food-processing",
    image: "7unitedricebeecp.jpg",
    externalLink: "https://www.primemeghalaya.com/7-united-rice-beer",
  },
  {
    slug: "baghmara-campers",
    businessName: "Baghmara Campers",
    entrepreneurName: "Mark Pantora M Sangma",
    district: "south-garo-hills",
    sector: "tourism-hospitality",
    image: "Baghmaracamperscp.jpg",
    externalLink: "https://www.primemeghalaya.com/baghmara-campers",
  },
  {
    slug: "bandasal-rural-resort",
    businessName: "BANDASAL RURAL RESORT",
    entrepreneurName: "Glorina N Sangma",
    district: "east-garo-hills",
    sector: "tourism-hospitality",
    image: "bandasalcp.jpg",
    externalLink: "https://www.primemeghalaya.com/bandasal-rural-resort/",
  },
  {
    slug: "ong-chnae-ktoi",
    businessName: "Ong chnae ktoi",
    entrepreneurName: "Paiaemdor LyngdohMawnai",
    district: "eastern-west-khasi-hills",
    sector: "handicrafts",
    image: "OngChnaeKtoicp.jpg",
    externalLink: "https://www.primemeghalaya.com/ong-chnae-ktoi/",
  },
  {
    slug: "mawrie-garments-manufacturer",
    businessName: "Mawrie Garments",
    entrepreneurName: "Fiyona Mawrie",
    district: "east-khasi-hills",
    sector: "textiles",
    image: "Mawriegarments5.jpg",
    externalLink: "https://www.primemeghalaya.com/mawrie-garments-manufacturer/",
  },
  {
    slug: "ecommerce-buddy",
    businessName: "Ecommerce Buddy",
    entrepreneurName: "Sudip Kumar Das",
    district: "west-garo-hills",
    sector: "technology-it",
    image: "ecommercebuddylogo.jpg",
    externalLink: "https://www.primemeghalaya.com/ecommerce-buddy/",
  },
  {
    slug: "vox-crest-media",
    businessName: "Vox Crest Media",
    entrepreneurName: "Ferdinand Rani",
    district: "east-khasi-hills",
    sector: "technology-it",
    image: "voxcrestmediacp.jpg",
    externalLink: "https://www.primemeghalaya.com/vox-crest-media/",
  },
  {
    slug: "whispering-pines",
    businessName: "Whispering Pines",
    entrepreneurName: "Candida Kharsyntiew",
    district: "east-khasi-hills",
    sector: "food-processing",
    image: "whisperingpines.jpg",
    externalLink: "https://www.primemeghalaya.com/whispering-pines/",
  },
  {
    slug: "marak-food-products",
    businessName: "Marak Food Products",
    entrepreneurName: "Tunila Ch. Marak",
    district: "east-garo-hills",
    sector: "food-processing",
    image: "Marakfoodproductscp.jpg",
    externalLink: "https://www.primemeghalaya.com/marak-food-products/",
  },
  {
    slug: "jency-handicrafts",
    businessName: "Jency Handicrafts",
    entrepreneurName: "Jency Suchiang",
    district: "east-jaintia-hills",
    sector: "handicrafts",
    image: "Sharakritprofile.jpg",
    externalLink: "https://www.primemeghalaya.com/jency-handicrafts/",
  },
  {
    slug: "sharak-rit",
    businessName: "Sharak Rit",
    entrepreneurName: "Amstrong Shylla",
    district: "south-west-khasi-hills",
    sector: "food-processing",
    image: "Sharakritrlcp.jpg",
    externalLink: "https://www.primemeghalaya.com/sharak-rit",
  },
  {
    slug: "daka-handicraft",
    businessName: "Daka Handicraft",
    entrepreneurName: "Dakaeishwami Shadap",
    district: "east-jaintia-hills",
    sector: "handicrafts",
    image: "Dakahandicraft.jpg",
    externalLink: "https://www.primemeghalaya.com/daka-handicraft",
  },
];

export function getProfile(slug: string): EntrepreneurProfile | undefined {
  return profiles.find((p) => p.slug === slug);
}
