export const SECTOR_LABELS: Record<string, string> = {
  "fashion": "Fashion",
  "handicrafts": "Handicrafts",
  "food-processing": "Food Processing",
  "tourism-hospitality": "Tourism & Hospitality",
  "textiles": "Textiles",
  "technology-it": "Technology & IT",
  "agriculture-horticulture": "Agriculture & Horticulture",
  "others": "Others",
};

export const DISTRICT_LABELS: Record<string, string> = {
  "east-khasi-hills": "East Khasi Hills",
  "west-khasi-hills": "West Khasi Hills",
  "eastern-west-khasi-hills": "Eastern West Khasi Hills",
  "south-west-khasi-hills": "South West Khasi Hills",
  "ri-bhoi": "Ri Bhoi",
  "east-jaintia-hills": "East Jaintia Hills",
  "west-jaintia-hills": "West Jaintia Hills",
  "east-garo-hills": "East Garo Hills",
  "west-garo-hills": "West Garo Hills",
  "south-garo-hills": "South Garo Hills",
  "north-garo-hills": "North Garo Hills",
};

export type EntrepreneurProfile = {
  slug: string;
  businessName: string;
  entrepreneurName: string;
  district: string;
  sector: string;
  image: string;
  description?: string;
  location?: string;
  email?: string;
  phone?: string;
  entity?: string;
  stage?: string;
  employment?: string;
  livesImpacted?: string;
  turnover?: string;
  govtFunding?: string;
  externalFunding?: string;
  socialImpact?: string;
  products?: string;
  externalLink: string;
};

export const profiles: EntrepreneurProfile[] = [
  {
    slug: "mohor",
    businessName: "Mohor",
    entrepreneurName: "Cordelia Kharsati",
    district: "east-khasi-hills",
    sector: "fashion",
    image: "Custommahor2.jpg",
    description: "Sustainable fashion startup founded by Cordelia Kharsati that upcycles waste fabric and uses eri silk to create eco-friendly clothing, accessories, and home décor while collaborating with local artisans.",
    location: "Mawlai Umjaiur, Block IV, East Khasi Hills",
    email: "cordeliacazel@gmail.com",
    phone: "9774066157",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "5",
    livesImpacted: "20",
    turnover: "₹3.76 Lakh",
    govtFunding: "₹1 Lakh",
    externalFunding: "₹3 Lakh",
    socialImpact: "Promotes sustainability and supports traditional craftsmanship by collaborating with local artisans, creating job opportunities and empowering communities in Meghalaya through upcycled fashion.",
    products: "Contemporary designer wear, Eri silk clothing, Upcycled fabric items, Accessories, Home décor",
    externalLink: "https://www.primemeghalaya.com/mohor/",
  },
  {
    slug: "btm-arts",
    businessName: "BTM Arts",
    entrepreneurName: "Bashanbok Myrboh",
    district: "east-khasi-hills",
    sector: "handicrafts",
    image: "btmarts.jpg",
    description: "Bashanbok Myrboh founded BTM Arts at 23 with no formal training, discovering his crafting talent during COVID-19. What began with selling a handmade house for ₹4,000 grew into a successful artisanal business capturing the regional beauty of Meghalaya.",
    location: "Mawryngkneng, East Khasi Hills",
    email: "bashanbokmyrboh@gmail.com",
    phone: "8798182483",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "4",
    livesImpacted: "16",
    turnover: "₹0.15 Lakh",
    govtFunding: "₹1 Lakh",
    socialImpact: "Creates job opportunities for local artisans, promotes traditional craftsmanship, preserves regional art forms, and supports the local economy through handmade mementos and home decor.",
    products: "Mementos, Home decor",
    externalLink: "https://www.primemeghalaya.com/btm-arts/",
  },
  {
    slug: "zero9-farms",
    businessName: "Zero9 Farms",
    entrepreneurName: "Bitchri Sekso Mebitchi R Marak, Damuda D Sangma",
    district: "south-garo-hills",
    sector: "food-processing",
    image: "Zero9Farms.jpg",
    description: "Bitchri Sekso Mebitchi R Marak founded Zero9 Farms, a food processing unit aimed at harnessing the richness of Meghalaya's natural resources to create high-quality products that cater to both the needs and desires of people.",
    location: "Balsrigittim, Baghmara, South Garo Hills District",
    email: "seksomarak12@gmail.com",
    phone: "8787326383",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "5",
    livesImpacted: "20",
    turnover: "₹5 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Supports local agriculture by sourcing from Meghalaya's natural resources, creating sustainable income opportunities for farmers and artisans while promoting the region's agricultural heritage.",
    products: "Jujube candy, Tamarind candy, Shredded meat & Pickle, Oyster Mushroom Pickle, Seasonal fruit wine, Marmalade, Passion Fruit & Pineapple Jam, Strawberry Jam",
    externalLink: "https://www.primemeghalaya.com/zero9-farms/",
  },
  {
    slug: "shangkai",
    businessName: "Shangkai",
    entrepreneurName: "Damanbha Khongstia",
    district: "east-khasi-hills",
    sector: "tourism-hospitality",
    image: "Shangkai4.jpg",
    description: "Tour and travel startup by rural youth from Meghalaya offering accommodation, transport, guides, packaged tours, and trekking services while highlighting lesser-known rural destinations around Sohra.",
    location: "Nohkalikai Khliehshnong, Sohra, East Khasi Hills District",
    email: "shangkaiindia@gmail.com",
    phone: "7005412901",
    entity: "Partnership",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹0.72 Lakh",
    govtFunding: "₹11 Lakh",
    externalFunding: "₹18 Lakh",
    socialImpact: "Promotes eco-tourism through e-bicycles enabling sustainable exploration of Sohra, reducing carbon emissions and encouraging environmental conservation while opening new economic avenues for rural youth.",
    products: "E-bicycles, Customised adventure tours, Accommodation packages, Trekking services",
    externalLink: "https://www.primemeghalaya.com/shangkai/",
  },
  {
    slug: "four-o-four",
    businessName: "Four O Four",
    entrepreneurName: "Eveleen E Marbaniang",
    district: "east-khasi-hills",
    sector: "handicrafts",
    image: "FourOFourProfile.jpg",
    description: "Four O Four, founded by Eveleen E Marbaniang in 2021, specializes in eco-friendly candles made from 100% soy wax and premium fragrance oils, offering handmade products at accessible price points.",
    location: "Mawlai Phudmawrie, East Khasi Hills District",
    email: "evmarbaniang@gmail.com",
    phone: "9774660495",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹3.02 Lakh",
    govtFunding: "₹1 Lakh",
    socialImpact: "Promotes sustainability through eco-friendly soy wax and premium oils while supporting environmentally conscious living with affordable, handmade products.",
    products: "Hand-poured scented soy candles, Unscented soy candles, Wax fresheners, Customized gift hampers",
    externalLink: "https://www.primemeghalaya.com/four-o-four",
  },
  {
    slug: "laichaphrang-handicraft",
    businessName: "Laichaphrang Handicraft",
    entrepreneurName: "Jenifer Suiam",
    district: "west-jaintia-hills",
    sector: "handicrafts",
    image: "Laichphrangprofile.jpg",
    description: "Creates eco-friendly bamboo and cane products focusing on sustainable kitchenware and décor. Each handcrafted piece showcases artisanship and promotes sustainability using locally sourced materials from West Jaintia Hills.",
    location: "Madankynsaw village, West Jaintia Hills District",
    email: "laichaphranghandicrafts@gmail.com",
    phone: "7005170694",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "58",
    livesImpacted: "232",
    turnover: "₹11.91 Lakh",
    govtFunding: "₹2.51 Lakh",
    externalFunding: "₹4.20 Lakh",
    socialImpact: "Uplifts communities by purchasing raw materials from students, training women in traditional handicraft-making, preserving local craftsmanship, and promoting sustainable resource use and environmental consciousness.",
    products: "Fruit baskets, Food containers, Cutlery trays, Flower stands, Hanging pots, Table mats, Tree houses, Traditional souvenirs (mawbynna)",
    externalLink: "https://www.primemeghalaya.com/laichaphrang-handicraft",
  },
  {
    slug: "hcollection",
    businessName: "Hcollection",
    entrepreneurName: "Hilarious Kharlyngdoh",
    district: "east-khasi-hills",
    sector: "fashion",
    image: "Hcollectionproduct.jpg",
    description: "Founded by Hilarious Kharlyngdoh, Hcollection specializes in manufacturing customized tote bags with unique, high-quality designs tailored to customer preferences and occasion.",
    location: "Mawlai Motsyiar, Shillong, East Khasi Hills District",
    email: "23hilariouskharlyngdoh@gmail.com",
    phone: "9863538737",
    entity: "Partnership",
    stage: "Early revenue",
    employment: "39",
    livesImpacted: "156",
    turnover: "₹3.15 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Empowers local artisans by providing opportunities in designing and manufacturing customized tote bags. Supports sustainable practices through reusable products while promoting creativity, entrepreneurship, and reducing environmental impact.",
    products: "Premium customized tote bags",
    externalLink: "https://www.primemeghalaya.com/hcollection/",
  },
  {
    slug: "jets-24x7",
    businessName: "JETS 24x7",
    entrepreneurName: "Pynskhemlang W Uriah",
    district: "east-khasi-hills",
    sector: "others",
    image: "jets2.jpg",
    description: "Bike taxi aggregator connecting passengers with riders for affordable, safe, and punctual commuting across Shillong. The platform operates without owning vehicles, focusing on app development, IT support, and network expansion.",
    location: "Jaiaw Upper Lansonalane, Shillong, East Khasi Hills District",
    email: "jets24x7official@gmail.com",
    phone: "7005145699",
    entity: "Partnership",
    stage: "Early revenue",
    employment: "132",
    livesImpacted: "528",
    turnover: "₹7.81 Lakh",
    govtFunding: "₹1 Lakh",
    socialImpact: "Simplifies daily commuting by connecting passengers with riders, ensuring affordability, safety, and punctuality. Creates employment for local associates while supporting a reliable transportation network across the community.",
    products: "Bike Taxi App (2-wheelers), Bike Taxi App (3-wheelers)",
    externalLink: "https://www.primemeghalaya.com/jets-24x7/",
  },
  {
    slug: "machine-khoh-kwai",
    businessName: "Machine khoh kwai",
    entrepreneurName: "Wanlang Lakuna",
    district: "east-khasi-hills",
    sector: "others",
    image: "Machinekhohkwaiimage.jpg",
    description: "Founded by Wanlang Lakuna, a B.Tech Mechanical Engineering graduate, during the COVID-19 pandemic. Inspired by his mother's struggles with manual betel nut processing, he developed an automated betel nut cutter that has since grown into a successful agri-tech venture.",
    location: "Lapalang, Dong Parmaw, Shillong, East Khasi Hills District",
    email: "wanlanglakuna@gmail.com",
    phone: "6033143697",
    stage: "MVP",
    employment: "2",
    livesImpacted: "8",
    govtFunding: "₹1 Lakh",
    socialImpact: "Significantly improved livelihoods by reducing labor-intensive manual work for betel nut processing, empowering local farmers, enhancing productivity, and supporting rural economic development in Meghalaya.",
    products: "Mechanised beetlenut peeling machine",
    externalLink: "https://www.primemeghalaya.com/machine-khoh-kwai/",
  },
  {
    slug: "zong-hi-i",
    businessName: "Zong Hi I",
    entrepreneurName: "Precious Star Tmung",
    district: "ri-bhoi",
    sector: "textiles",
    image: "zonghii.jpg",
    description: "Pioneer in eri silk dyeing and weaving in Meghalaya, specializing in natural dyeing using local materials and traditional looms. Renowned for producing Ryndia (Ahimsa/Peace Silk) that avoids harming silkworms — the name means \"It's Our Own\" in Khasi.",
    location: "Diwon, Umden Nongpoh, Ri-Bhoi District",
    email: "preciousstartmung@gmail.com",
    phone: "8131979588",
    entity: "Partnership",
    stage: "In Revenue",
    employment: "22",
    livesImpacted: "88",
    turnover: "₹32.02 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Promotes eco-friendly practices using natural dyes, supports skilled artisans with fair livelihoods, creates employment, and preserves traditional spinning, dyeing, and weaving techniques while protecting Meghalaya's cultural heritage.",
    products: "Ryndia (Ahimsa/Peace Silk) fabrics, Naturally dyed eri silk textiles, Traditional loin loom woven fabrics, Fly shuttle loom woven fabrics, Handwoven scarves and shawls",
    externalLink: "https://www.primemeghalaya.com/zong-hi-i",
  },
  {
    slug: "surwandiam-enterprise-av-production",
    businessName: "Surwandiam Enterprise AV Production",
    entrepreneurName: "Pondermost Khongkliam",
    district: "east-khasi-hills",
    sector: "others",
    image: "SurwandiamEnterprise3.jpg",
    description: "Pioneer studio established in 2005 that underwent significant transformation under new leadership in 2021, driving creative growth and community benefits. Provides full-scale audio and video production services to the Pynursla region.",
    location: "Wahumrem Pynursla, East Khasi Hills District",
    email: "khorchynnam@gmail.com",
    phone: "8131025070",
    entity: "Partnership",
    stage: "Early revenue",
    employment: "19",
    livesImpacted: "76",
    turnover: "₹6.75 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Serves as a catalyst for creativity and economic growth in the community, empowering local talent through skill development platforms and financial independence opportunities in the creative sector.",
    products: "Audio recording, Video production, Film editing & post-production, Music production, Studio rental, Creative media solutions",
    externalLink: "https://www.primemeghalaya.com/surwandiam-enterprise-av-production",
  },
  {
    slug: "ceefle-venture",
    businessName: "Ceefle Venture",
    entrepreneurName: "Babitdor Kharsohtun",
    district: "east-khasi-hills",
    sector: "food-processing",
    image: "ceefleprofile.jpg",
    description: "Founded by Babitdor Kharsohtun, Ceefle Venture offers premium natural products sourced from Meghalaya's rich biodiversity — from Lakadong turmeric to wildflower honey and native spices.",
    location: "Mawpat, Circle 3, Shillong, East Khasi Hills District",
    email: "babit.k@ceefle.com",
    phone: "8787840266",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "7",
    livesImpacted: "28",
    turnover: "₹6.77 Lakh",
    govtFunding: "₹1 Lakh",
    externalFunding: "₹2.3 Lakh",
    socialImpact: "Promotes health and wellness through natural products while supporting local farmers, encouraging sustainable agricultural practices, and creating livelihood opportunities for local youth.",
    products: "Lakadong Turmeric Powder & Slices, Ingmakhir Ginger Powder & Slices, Black Pepper Powder & Whole, Bayleaf Powder & Whole, Cinnamon Powder & Sticks, Wildflower Honey",
    externalLink: "https://www.primemeghalaya.com/ceefle-venture",
  },
  {
    slug: "crochet-haven",
    businessName: "Crochet Haven",
    entrepreneurName: "Ibajanai Lyngdoh",
    district: "east-khasi-hills",
    sector: "handicrafts",
    image: "CrochetHavenprofile.jpg",
    description: "Founded by Ibajanai Lyngdoh, Crochet Haven specializes in handmade crochet items — from stylish tops and flower bouquets to unique bags and accessories. The studio also accepts custom orders and runs creative crochet workshops.",
    location: "Nongrimbah, Laitumkhrah, East Khasi Hills District",
    email: "crochethaven11@gmail.com",
    phone: "6009149820",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "4",
    livesImpacted: "16",
    turnover: "₹0.93 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Empowers rural women through skill training and employment in handmade crochet. Promotes sustainability, supports creativity, and builds community connections through its unique café and creative workshop space.",
    products: "Cardigans, Tops, Bralettes, Skirts, Berets & Beanies, Mufflers, Flower bouquets, Amigurumi keychains, Tote bags, Sling bags, Mini purses, Laptop bags, Plushies",
    externalLink: "https://www.primemeghalaya.com/crochet-haven",
  },
  {
    slug: "rose-tegite",
    businessName: "Rose Tegite",
    entrepreneurName: "Rosemary T Sangma",
    district: "south-garo-hills",
    sector: "fashion",
    image: "RoseTegiteprofile.jpg",
    description: "Clothing brand by Rosemary T Sangma specializing in upcycled and eco-conscious fashion pieces as traditional fusion wear, celebrating Garo cultural heritage through distinctive designs and textures.",
    location: "Nongal Bibra, South Garo Hills District",
    email: "rosemarysangma777@gmail.com",
    phone: "8861473381",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "1",
    livesImpacted: "4",
    turnover: "₹1.92 Lakh",
    govtFunding: "₹8 Lakh",
    socialImpact: "Promotes sustainable fashion through material upcycling and waste reduction while celebrating Garo heritage, creating opportunities for local artisans and fostering environmental awareness in the community.",
    products: "Dakmanda, Traditional Shawl, Dresses and Tops",
    externalLink: "https://www.primemeghalaya.com/rose-tegite",
  },
  {
    slug: "salgro-wood-carving",
    businessName: "Salgro Wood-Carving",
    entrepreneurName: "Thengku Sangma",
    district: "north-garo-hills",
    sector: "handicrafts",
    image: "SalgroWoodCarvingimg.jpg",
    description: "Specializes in sculpting and carving various shapes, idols, and figurines dedicated to preserving the Garo tradition of wood carving and passing this dying art to younger generations.",
    location: "Mendal P.O., Resubelpara, North Garo Hills District",
    email: "Thengkusangma44@gmail.com",
    phone: "9863217691",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "1",
    livesImpacted: "4",
    turnover: "₹1.37 Lakh",
    govtFunding: "₹1 Lakh",
    socialImpact: "Preserves Garo community wood carving traditions and provides livelihood opportunities to local artisans, empowering them with heritage skills and sustainable employment.",
    products: "Wooden showpieces, Tree houses, Wooden wall decor, Earrings, Keychains, Pitcher plants, Traditional houses, Flower pot stands, Human figurines",
    externalLink: "https://www.primemeghalaya.com/salgro-wood-carving",
  },
  {
    slug: "medira-handloom",
    businessName: "Medira handloom",
    entrepreneurName: "Medira G Sangma",
    district: "west-garo-hills",
    sector: "textiles",
    image: "Medirahandloomprofile.jpg",
    description: "Medira G Sangma founded Medira Handloom specializing in A'chik traditional dresses with authentic Dakmanda sets, showcasing rich cultural heritage crafted with meticulous attention to detail.",
    location: "Balsanang, Tura, West Garo Hills District",
    email: "sangmamedira@gmail.com",
    phone: "9863005844",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "7",
    livesImpacted: "28",
    turnover: "₹11.83 Lakh",
    govtFunding: "₹8.50 Lakh",
    externalFunding: "₹2.50 Lakh",
    socialImpact: "Empowers local artisans by preserving A'chik traditional dress-making techniques, sustaining Garo cultural heritage and supporting the local economy through handcrafted garment production.",
    products: "Dakmanda single piece, Dakmanda shawl, Top set",
    externalLink: "https://www.primemeghalaya.com/medira-handloom",
  },
  {
    slug: "cassey-turima",
    businessName: "Cassey Turima",
    entrepreneurName: "Cassey Turima M Marak",
    district: "west-garo-hills",
    sector: "handicrafts",
    image: "CasseyTurima1.jpg",
    description: "Brand specializing in luxury fashion bags crafted from crochet and unique yarns, offering high-quality stylish designs at accessible price points from Tura.",
    location: "Sunny Hills, New Tura, West Garo Hills District",
    email: "turimamarak@gmail.com",
    phone: "8119802406",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹5.22 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Supports local artisans through crafting opportunities, promotes traditional crochet techniques, enhances community livelihoods, preserves cultural craftsmanship, and encourages sustainable fashion practices.",
    products: "Handbag, Slingbag, Crossbody bag, Mini bag, Keychains, Charms, Baby basket",
    externalLink: "https://www.primemeghalaya.com/cassey-turima",
  },
  {
    slug: "rising-26-9",
    businessName: "Rising 26-9",
    entrepreneurName: "Nichang Momin",
    district: "west-garo-hills",
    sector: "handicrafts",
    image: "Risingcp.jpg",
    description: "Handmade crochet bag business creating unique designs using materials like macrame, beads, and nylon rope, combining creativity with quality craftsmanship from Tura.",
    location: "Dobasipara, Tura, West Garo Hills District",
    email: "nichangmomin01@gmail.com",
    phone: "9366580497",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "1",
    livesImpacted: "4",
    turnover: "₹1.57 Lakh",
    govtFunding: "₹1 Lakh",
    socialImpact: "Promotes sustainable fashion through handmade products, supports local craftsmanship, provides economic opportunities for artisans, and preserves traditional textile techniques.",
    products: "Macrame bags, Bead bags, Crochet bags, Keychains",
    externalLink: "https://www.primemeghalaya.com/rising-26-9",
  },
  {
    slug: "wedoa-chocolate",
    businessName: "WEDOA chocolate",
    entrepreneurName: "Tiara Roxettee M Sangma",
    district: "west-garo-hills",
    sector: "food-processing",
    image: "WEDOAcp.jpg",
    description: "Founded by Tiara Roxettee M Sangma, Wedoa Chocolates offers clean-label artisanal chocolates made without soy lecithin or synthetic emulsifiers, incorporating local Meghalaya ingredients like black sesame and regional fruits.",
    location: "Upper Wadanang, Tura, West Garo Hills District",
    email: "wedoachocolate@gmail.com",
    phone: "9366358386",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "1",
    livesImpacted: "4",
    turnover: "₹2 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Uplifts local farming communities by sourcing ingredients like black sesame and fruits directly from Meghalaya, supporting sustainable agriculture and empowering regional farmers with stable income.",
    products: "Clean-label dark chocolates, Black sesame-infused chocolates, Fruit-flavored chocolates, Handcrafted artisanal chocolate bars",
    externalLink: "https://www.primemeghalaya.com/wedoa-chocolate",
  },
  {
    slug: "shillong-agro-solutions",
    businessName: "Shillong Agro Solutions",
    entrepreneurName: "Wanlambok Wanshuwa Kshiar Shadap",
    district: "east-khasi-hills",
    sector: "food-processing",
    image: "Shillongagrosolutions3.jpg",
    description: "Specializes in the cultivation of oyster, button, and shitake mushrooms using sustainable farming practices, focusing on high-quality produce and local market supply across Shillong.",
    location: "Laitkor Pamsubon, Shillong, East Khasi Hills District",
    email: "shillongagrosolutions@gmail.com",
    phone: "8257831884",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "18",
    livesImpacted: "72",
    turnover: "₹5.25 Lakh",
    govtFunding: "₹50.50 Lakh",
    socialImpact: "Supports sustainable agriculture by cultivating high-quality mushrooms and supplying fresh produce to local markets, contributing to the local economy and promoting modern farming techniques.",
    products: "Oyster mushrooms, Button mushrooms, Shitake mushrooms",
    externalLink: "https://www.primemeghalaya.com/shillong-agro-solutions/",
  },
  {
    slug: "ls-food-products",
    businessName: "LS.Food Products",
    entrepreneurName: "Thruslinda S Sangma",
    district: "west-garo-hills",
    sector: "food-processing",
    image: "Lsfoodproductcp.jpg",
    description: "Women-led enterprise specializing in food products like chips, pickles, and exotic local fruit juices and wine, focusing on locally sourced Garo Hills ingredients and preserving Meghalaya's culinary traditions.",
    location: "Rongkon Songgital Tura, West Garo Hills District",
    email: "trustlindassangma@gmail.com",
    phone: "8731011893",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹3.5 Lakh",
    govtFunding: "₹5 Lakh",
    socialImpact: "Empowers women entrepreneurs, promotes local produce, and preserves Meghalaya's culinary heritage while supporting rural livelihoods and strengthening community-based economic growth.",
    products: "Seasonal fruit chips, Fruit juice and wine, Pickles, Marmalade and jam",
    externalLink: "https://www.primemeghalaya.com/ls-food-products/",
  },
  {
    slug: "mei-ramew-cafe-jingbam-tynrai",
    businessName: "Mei-Ramew Cafe",
    entrepreneurName: "Plantina Mujai",
    district: "ri-bhoi",
    sector: "tourism-hospitality",
    image: "Meiramewcafecp.jpg",
    description: "Indigenous café celebrating local cuisine by innovating traditional recipes with locally sourced ingredients from Ri-Bhoi District. Promotes cultural diversity, sustainable livelihoods, and serves as a hub for community engagement and tourism.",
    location: "Khweng village, Nongpoh, Ri-Bhoi District",
    email: "kmenmujai@gmail.com",
    phone: "8618650483",
    entity: "Partnership",
    stage: "In Revenue",
    employment: "20",
    livesImpacted: "80",
    turnover: "₹35.3 Lakh",
    govtFunding: "₹7 Lakh",
    socialImpact: "Strengthens the local economy by supporting rural farmers, showcases regional art and traditions, promotes cultural diversity and sustainable livelihoods, and serves as a community hub for tourism.",
    products: "Slow cooked traditional dishes, Pickles, Traditional herbs",
    externalLink: "https://www.primemeghalaya.com/mei-ramew-cafe-jingbam-tynrai/",
  },
  {
    slug: "boba-bae",
    businessName: "Boba Bae",
    entrepreneurName: "Lyzander Sohkhlet",
    district: "east-khasi-hills",
    sector: "food-processing",
    image: "Bobabaecp.jpg",
    description: "Boba Bae redefines bubble tea by blending Meghalaya's rich heritage with global innovation, specializing in flavors inspired by local orchards and using seaweed popping bobas sourced from the region.",
    location: "Laitumkhrah, Shillong, East Khasi Hills District",
    email: "lyzanedgar.co@gmail.com",
    phone: "9863355084",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "7",
    livesImpacted: "28",
    turnover: "₹10.5 Lakh",
    govtFunding: "₹17 Lakh",
    socialImpact: "Supports local farmers through sustainable sourcing from Meghalaya's orchards and provides employment to single mothers and individuals over 40, creating inclusive economic opportunities.",
    products: "Strawberry bubble tea, Peach bubble tea, Blueberry bubble tea, Seaweed popping bobas, Locally inspired fruit-based bubble teas",
    externalLink: "https://www.primemeghalaya.com/boba-bae/",
  },
  {
    slug: "your-tee-your-style",
    businessName: "Your Tee Your Style",
    entrepreneurName: "Shano Chelsy M Sangma",
    district: "west-garo-hills",
    sector: "others",
    image: "Yourteeyourstylecp.jpg",
    description: "Specializes in customized art on a variety of products including T-shirts, tote bags, hoodies, mugs, and bottles — each with unique, personalized designs that express individual identity.",
    location: "Burny Hills, Tura, West Garo Hills District",
    email: "shanochelz@icloud.com",
    phone: "9362850960",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹2.5 Lakh",
    govtFunding: "₹11 Lakh",
    socialImpact: "Empowers local artists by providing a platform to showcase creativity through custom designs. Encourages self-expression, supports sustainable practices using reusable products, and contributes to the local economy through employment.",
    products: "Customised T-shirts, Tote bags, Hoodies, Mugs, Bottles",
    externalLink: "https://www.primemeghalaya.com/your-tee-your-style/",
  },
  {
    slug: "digital-fuel",
    businessName: "Digital Fuel",
    entrepreneurName: "Mansha Sharma",
    district: "east-khasi-hills",
    sector: "technology-it",
    image: "digitalfuelcp.jpg",
    description: "Mansha Sharma and Pinak Deb co-founded Digital Fuel, offering affordable digital marketing services. Their complementary skills in media and commerce enabled the startup to expand beyond Shillong to clients across India.",
    location: "Bomfyl Road Laitumkhrah, East Khasi Hills District",
    email: "care.digitalfuel@gmail.com",
    phone: "9862256900",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "12",
    livesImpacted: "48",
    turnover: "₹17.48 Lakh",
    govtFunding: "₹1 Lakh",
    socialImpact: "Supports businesses through affordable digital marketing, promotes local talent, creates employment opportunities, and contributes to economic growth via accessible online solutions.",
    products: "Branding & logo design, Social media promotions, Video production, Content creation, Marketing consultation",
    externalLink: "https://www.primemeghalaya.com/digital-fuel/",
  },
  {
    slug: "soola",
    businessName: "Soola",
    entrepreneurName: "Glorisa Kalra War & Wanda Kharakor",
    district: "east-khasi-hills",
    sector: "fashion",
    image: "soolaprofile.jpg",
    description: "Inclusive clothing brand embracing diversity in fashion, offering styles for all shapes, sizes, and genders with full customization services for special events and everyday wear.",
    location: "Laitumkhrah Modrina Mansion, Shillong, East Khasi Hills District",
    email: "officialsoola@gmail.com",
    phone: "9366984220",
    entity: "Partnership",
    stage: "Early revenue",
    employment: "2",
    livesImpacted: "8",
    turnover: "₹4.89 Lakh",
    govtFunding: "₹7 Lakh",
    socialImpact: "Promotes inclusivity and self-expression through diversity in fashion, empowers local artisans via employment and skill development, fosters body positivity, and strengthens community pride.",
    products: "Customised designer wear",
    externalLink: "https://www.primemeghalaya.com/soola/",
  },
  {
    slug: "solipsis-design",
    businessName: "Solipsis Design",
    entrepreneurName: "Rundolf Mawlieh",
    district: "east-khasi-hills",
    sector: "technology-it",
    image: "solipsiscp.jpg",
    description: "Provides strategic services in packaging design, product prototyping, and customized marketing campaigns, helping businesses in Meghalaya and beyond enhance brand visibility and reach.",
    location: "Lower Cleve Colony, Shillong, East Khasi Hills District",
    email: "ashishsahashillong@gmail.com",
    phone: "8882608208",
    entity: "Pvt. Ltd",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹2.78 Lakh",
    govtFunding: "₹1 Lakh",
    socialImpact: "Empowers businesses through strategic packaging and tailored marketing. Collaborates with local enterprises to enhance brand visibility and supports regional economic growth through design innovation.",
    products: "Packaging design, Product prototyping, Customized marketing strategies, Branding and identity development",
    externalLink: "https://www.primemeghalaya.com/solipsis-design",
  },
  {
    slug: "rida-sten-food-cottage",
    businessName: "Rida Sten Food Cottage",
    entrepreneurName: "Niwania I Sten",
    district: "west-jaintia-hills",
    sector: "food-processing",
    image: "Ridastenfoodcottagecp.jpg",
    description: "Offers a variety of snacks and beverages including chips in unique flavors and locally inspired drinks. One of the first ventures to commercially process and promote rice tea — a traditional Jaintia Hills beverage.",
    location: "Sahsniang B, Laskein, West Jaintia Hills District",
    email: "niwansten75@gmail.com",
    phone: "8414088015",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "2",
    livesImpacted: "8",
    turnover: "₹2.3 Lakh",
    govtFunding: "₹1 Lakh",
    externalFunding: "₹0.5 Lakh",
    socialImpact: "Supports local farmers and promotes Jaintia Hills cultural heritage through traditional food products, strengthening rural economies and creating sustainable livelihood opportunities within the community.",
    products: "Red Rice Tea, Jackfruit chips, Banana chips, Tapioca chips, Potato chips",
    externalLink: "https://www.primemeghalaya.com/rida-sten-food-cottage",
  },
  {
    slug: "little-sunshine-boutique-and-nursery",
    businessName: "Little SunShine Boutique and Nursery",
    entrepreneurName: "Boblyford Thangkhiew",
    district: "east-khasi-hills",
    sector: "agriculture-horticulture",
    image: "Littlesunshinecp.jpg",
    description: "Specializes in ready-to-display succulents and cacti tailored to customer needs, with growing offerings in indoor/outdoor plants, garden landscaping, and seasonal decorations across Shillong.",
    location: "Nongkseh, 3rd Mile, Kynton Upper Shillong, East Khasi Hills District",
    email: "boblyford82@yahoo.com",
    phone: "9632471482",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "2",
    livesImpacted: "8",
    turnover: "₹4.45 Lakh",
    govtFunding: "₹6 Lakh",
    socialImpact: "Supports local plant cultivation and promotes sustainable living. Provides livelihood to school dropouts and encourages eco-friendly décor and green spaces in homes and businesses.",
    products: "Indoor & outdoor plants, Wedding return gifts, Gift hampers, Gardening services, Landscaping services, Potted plant rentals",
    externalLink: "https://www.primemeghalaya.com/little-sunshine-boutique-and-nursery/",
  },
  {
    slug: "sakhiona",
    businessName: "Sakhiona",
    entrepreneurName: "Sakhihok Lamare",
    district: "west-jaintia-hills",
    sector: "food-processing",
    image: "Sakhionaprofile.jpg",
    description: "Offers traditional food products including pickles, candies, juices, squashes, wines, jams, and spices made with natural ingredients sourced from West Jaintia Hills.",
    location: "Raliang Umpasait Karumpani Road, West Jaintia Hills District",
    email: "sakhihoklamare20@gmail.com",
    phone: "8787837297",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "9",
    livesImpacted: "36",
    turnover: "₹2.15 Lakh",
    govtFunding: "₹1 Lakh",
    externalFunding: "₹1.5 Lakh",
    socialImpact: "Promotes Meghalaya's culinary heritage through locally sourced traditional food production, supports local farmers, creates employment opportunities, and encourages sustainable food practices.",
    products: "Pickles (vegetables, fruits, dry fish, meat), Candies (ginger, pumpkin, gooseberry), Juices (pineapple, myrica, lemon), Squashes (mulberry, blackberry), Wines (mulberry, gooseberry, pineapple), Jams (jackfruit, pineapple), Spices (turmeric, sumac, zanthoxylum seeds)",
    externalLink: "https://www.primemeghalaya.com/sakhiona/",
  },
  {
    slug: "bithon-bamboo",
    businessName: "Bithon Bamboo",
    entrepreneurName: "Bithon D Sangma",
    district: "east-garo-hills",
    sector: "handicrafts",
    image: "Bithonbamboocp.jpg",
    description: "Bithon D Sangma founded Bithon Bamboo, specializing in unique bamboo and cane products including tea ware, cutlery, baskets, furniture, and traditional Garo musical instruments, blending heritage with contemporary design.",
    location: "William Nagar, East Garo Hills District",
    email: "bithonsangma108@gmail.com",
    phone: "9863669561",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "5",
    livesImpacted: "20",
    turnover: "₹4.84 Lakh",
    govtFunding: "₹1 Lakh",
    socialImpact: "Creates unique bamboo and cane products promoting sustainable handcrafted items while showcasing the versatility of natural materials and preserving Garo bamboo crafting traditions.",
    products: "Tree houses, Bamboo cutlery, Pen holders, Flower vases, Lamps, Keychains, Bamboo furniture, Traditional instruments, Cups and jugs, Tray and winnowing tray",
    externalLink: "https://www.primemeghalaya.com/bithon-bamboo",
  },
  {
    slug: "nengminja-industry",
    businessName: "Nengminja industry",
    entrepreneurName: "Briana Novemchi N. Sangma",
    district: "west-garo-hills",
    sector: "fashion",
    image: "Nengminjaindustrycp.jpg",
    description: "Offers Garo traditional outfits and accessories for various occasions alongside home furnishings with a traditional touch, showcasing and celebrating A'chik cultural heritage from Tura.",
    location: "House No. 124, Asillanggre Upper Chandmari, Tura, West Garo Hills District",
    email: "sangmavem@gmail.com",
    phone: "9366965672",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "5",
    livesImpacted: "20",
    turnover: "₹5.8 Lakh",
    govtFunding: "₹2 Lakh",
    externalFunding: "₹0.50 Lakh",
    socialImpact: "Preserves and promotes Garo culture through traditional attire and home furnishings, supports local artisans, and contributes to community pride and cultural identity.",
    products: "Hair bows, Scrunchies, Hairbands, Lounge wear, Co-ord sets, Skirts, Shirts, Bucket hats, Bags, Frames",
    externalLink: "https://www.primemeghalaya.com/nengminja-industry/",
  },
  {
    slug: "level-up-virtual-experience-cafe",
    businessName: "Level Up",
    entrepreneurName: "Yashraj A. Sangma",
    district: "west-garo-hills",
    sector: "technology-it",
    image: "Levelupcp.jpg",
    description: "Level Up is a recreational space where gaming, exploring, exercising, and learning converge through immersive virtual reality experiences, bringing cutting-edge tech entertainment to Tura.",
    location: "K.A. Road, Chandmari, Tura, West Garo Hills District",
    email: "y99y2jy99@gmail.com",
    phone: "7229832166",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹4.88 Lakh",
    govtFunding: "₹10 Lakh",
    socialImpact: "Provides community engagement through recreational activities, encourages skill development, promotes mental wellness, and creates job opportunities in technology and entertainment sectors.",
    products: "VR experiences, Racing Simulator, PS5 gaming, Food & beverages",
    externalLink: "https://www.primemeghalaya.com/level-up-virtual-experience-cafe/",
  },
  {
    slug: "sj-visual-art",
    businessName: "SJ Visual Art",
    entrepreneurName: "Saljagring N Arengh",
    district: "west-garo-hills",
    sector: "others",
    image: "SJvisualartcp.jpg",
    description: "Specializes in creating unique paintings including portraits, landscapes, and murals, combining creativity and skill to deliver exceptional artwork that captures the character of people and places.",
    location: "Tura Spring Hills, West Garo Hills District",
    email: "jagringarengh2018@gmail.com",
    phone: "8794153309",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "1",
    livesImpacted: "4",
    turnover: "₹3.85 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Supports local artists by providing a platform to showcase talent, creates employment opportunities in the arts, preserves cultural heritage through artistic themes, and enriches community identity.",
    products: "Oil paintings, Acrylic paintings, Wall paintings & murals",
    externalLink: "https://www.primemeghalaya.com/sj-visual-art",
  },
  {
    slug: "houseofura-studio",
    businessName: "houseofura.studio",
    entrepreneurName: "Divya K Marak",
    district: "west-garo-hills",
    sector: "fashion",
    image: "houseofurastudiocp.jpg",
    description: "A one-stop destination for fashion, design, and styling needs — simplifying access to both everyday and aspirational fashion through creative made-to-order garments and customized accessories from Tura.",
    location: "Fancy Valley, Tura, West Garo Hills District",
    email: "divyamarak3@gmail.com",
    phone: "8837046144",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹1.71 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Offers made-to-order garments and customized accessories while creating sustainable livelihood opportunities for local artisans. Encourages creativity, supports skill development, and promotes financial independence.",
    products: "Made-to-order garments (dresses, kurtis, kurti sets), Scarfs, Keychains, Vanity bags, Pencil pouches, Rag dolls, Teddy bears, Gift items",
    externalLink: "https://www.primemeghalaya.com/houseofura-studio",
  },
  {
    slug: "the-tea-story",
    businessName: "The Tea Story",
    entrepreneurName: "Bibian Momin",
    district: "west-garo-hills",
    sector: "food-processing",
    image: "Theteastorycp.jpg",
    description: "Tea manufacturer offering a wide range of premium tea blends to suit various preferences and market segments, focusing on high-quality tea and sustainability in sourcing from Garo Hills.",
    location: "Rongkhon Songgital, Tura, West Garo Hills District",
    email: "therealteastory@gmail.com",
    phone: "8258849207",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "10",
    livesImpacted: "40",
    turnover: "₹5.37 Lakh",
    govtFunding: "₹9 Lakh",
    externalFunding: "₹1.20 Lakh",
    socialImpact: "Promotes sustainable livelihoods by sourcing tea locally, supporting farmers, enhancing community development, and preserving regional tea heritage through quality processing.",
    products: "Orange tea, Kahwa tea, Mint burst, Ginger tea, Lemon Grass tea, Green tea, Orthodox tea, Special tea, Tea gift boxes",
    externalLink: "https://www.primemeghalaya.com/the-tea-story/",
  },
  {
    slug: "durama-handicrafts",
    businessName: "Durama handicrafts",
    entrepreneurName: "Brithing C Marak",
    district: "south-garo-hills",
    sector: "handicrafts",
    image: "Duramahandicrafts2.jpg",
    description: "Durama Handicrafts represents a unique masterpiece of bamboo and cane products including traditional Garo musical instruments, celebrating cultural craftsmanship from South Garo Hills.",
    location: "Gongjagre, Baghmara, South Garo Hills District",
    email: "brithing.c.marak@gmail.com",
    phone: "6009077985",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹3.5 Lakh",
    govtFunding: "₹7 Lakh",
    socialImpact: "Preserves and promotes the rich cultural heritage of the Garo community through bamboo and cane products including traditional musical instruments, creating livelihood opportunities and sustaining traditional craftsmanship for future generations.",
    products: "Bamboo baskets, Traditional instruments, Décor items",
    externalLink: "https://www.primemeghalaya.com/durama-handicrafts",
  },
  {
    slug: "vision-to-arts-and-fashion-design",
    businessName: "Vision To Arts And Fashion Design",
    entrepreneurName: "Larimika Syrti",
    district: "east-jaintia-hills",
    sector: "fashion",
    image: "larimikacp.jpg",
    description: "Founded in 2018, this fashion and arts venture blends design with personal expression, combining academic expertise in fashion and arts to create a platform celebrating creativity and individuality in East Jaintia Hills.",
    location: "VAFD by Larimika, Block Road, Khliehriat West, East Jaintia Hills District",
    email: "syrtilarimika@gmail.com",
    phone: "6009042862",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "22",
    livesImpacted: "88",
    turnover: "₹17.05 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Nurtures creativity and empowers local artisans and women by blending traditional craftsmanship with contemporary design, providing economic opportunities, skill development, and cultural preservation.",
    products: "Custom fashion design, Art-inspired clothing, Fashion styling services, Design consultations, Personalized accessories, Creative workshops",
    externalLink: "https://www.primemeghalaya.com/vision-to-arts-and-fashion-design/",
  },
  {
    slug: "m-s-sari-soap",
    businessName: "M/S SARI SOAP",
    entrepreneurName: "Dau Ruhi Sari",
    district: "west-jaintia-hills",
    sector: "others",
    image: "Sarisoapprofilr.jpg",
    description: "Specializes in manufacturing high-quality laundry soap supplying to 34 retail outlets across the region, ensuring accessibility and reliability for customers throughout West Jaintia Hills.",
    location: "Thadmuthlong A, West Jaintia Hills District",
    email: "dauruhisari8@gmail.com",
    phone: "9612355799",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "2",
    livesImpacted: "8",
    turnover: "₹13.14 Lakh",
    govtFunding: "₹4 Lakh",
    socialImpact: "Creates job opportunities in manufacturing and distribution, supporting local livelihoods. Ensures community access to quality laundry products and helps strengthen local economies and small businesses in the region.",
    products: "Laundry soap, Detergent",
    externalLink: "https://www.primemeghalaya.com/m-s-sari-soap/",
  },
  {
    slug: "lokki-food-products",
    businessName: "Lokki Food Products",
    entrepreneurName: "Lokki M Sangma",
    district: "east-garo-hills",
    sector: "food-processing",
    image: "lokkifoodproductscp.jpg",
    description: "Founded by Lokki M Sangma, Lokki Food Products offers a variety of locally sourced food items from East Garo Hills, committed to promoting local produce and delivering fresh, high-quality products to customers.",
    location: "Bolkinggre, Williamnagar, East Garo Hills District",
    email: "lokkisangma@gmail.com",
    phone: "7005990781",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "6",
    livesImpacted: "24",
    turnover: "₹1.66 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Supports local farmers by sourcing ingredients directly from the region, boosting the local economy. Promotes sustainable farming practices and creates community income opportunities while encouraging consumption of locally grown produce.",
    products: "Fruit wine, Fruit chips, Juice",
    externalLink: "https://www.primemeghalaya.com/lokki-food-products",
  },
  {
    slug: "oihelp",
    businessName: "OiHelp",
    entrepreneurName: "Avik Chakraborty",
    district: "west-garo-hills",
    sector: "technology-it",
    image: "oihelpcp.jpg",
    description: "Founded by Avik Chakraborty, OiHelp is an online retail platform providing food delivery, grocery delivery, retail products, and pick-up/drop-off services across Tura.",
    location: "48, Fancy Valley, Tura, West Garo Hills District",
    email: "avik331@gmail.com",
    phone: "9500090827",
    entity: "Pvt. Limited",
    stage: "Early revenue",
    employment: "12",
    livesImpacted: "48",
    turnover: "₹18.14 Lakh",
    govtFunding: "₹10 Lakh",
    externalFunding: "₹5.65 Lakh",
    socialImpact: "Supports local businesses, promotes economic growth, and empowers communities by offering convenient last-mile delivery services that connect consumers with local vendors.",
    products: "Online food delivery, Grocery delivery, Retail products, Pick-up & drop-off services",
    externalLink: "https://www.primemeghalaya.com/oihelp",
  },
  {
    slug: "7-united-rice-beer",
    businessName: "7 United Rice Beer",
    entrepreneurName: "Keenan K Marak",
    district: "west-garo-hills",
    sector: "food-processing",
    image: "7unitedricebeecp.jpg",
    description: "Keenan K Marak founded 7 United Rice Brew, blending tradition with modern innovation to redefine rice brew — a fresh take on this traditional Garo beverage that honors its cultural roots while appealing to contemporary tastes.",
    location: "Matchakolgre, Tura, West Garo Hills District",
    email: "keenanmrk@gmail.com",
    phone: "7619353739",
    entity: "Pvt. Limited",
    stage: "In Revenue",
    employment: "14",
    livesImpacted: "56",
    turnover: "₹24.22 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Supports local farmers by sourcing ingredients from the region, providing steady income. Revives and modernizes a traditional beverage, creating new community opportunities while preserving Meghalaya's cultural heritage.",
    products: "Premium rice beer",
    externalLink: "https://www.primemeghalaya.com/7-united-rice-beer",
  },
  {
    slug: "baghmara-campers",
    businessName: "Baghmara Campers",
    entrepreneurName: "Mark Pantora M Sangma",
    district: "south-garo-hills",
    sector: "tourism-hospitality",
    image: "Baghmaracamperscp.jpg",
    description: "Specializes in personalized tour packages focusing on showcasing the natural beauty of the Garo Hills and Northeast destinations, offering travelers unique and memorable experiences through eco-conscious tourism.",
    location: "Baghmara, South Garo Hills District",
    email: "Baghmaracampers@gmail.com",
    phone: "6290979563",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "16",
    livesImpacted: "64",
    turnover: "₹19.25 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Promotes sustainable tourism showcasing the region's natural beauty and culture. Supports local guides, drivers, and homestays while encouraging eco-friendly travel and cultural exchange.",
    products: "Personalized tour packages, Garo Hills eco-tours, Adventure camping, Cultural & heritage tours, Wildlife exploration trips, Northeast India travel packages",
    externalLink: "https://www.primemeghalaya.com/baghmara-campers",
  },
  {
    slug: "bandasal-rural-resort",
    businessName: "BANDASAL RURAL RESORT",
    entrepreneurName: "Glorina N Sangma",
    district: "east-garo-hills",
    sector: "tourism-hospitality",
    image: "bandasalcp.jpg",
    description: "Eco-friendly resort in the Garo Hills offering guests the opportunity to unwind and immerse in serene nature while promoting sustainable hospitality and farming practices.",
    location: "Rongribo Chibolgre, Samanda, East Garo Hills District",
    email: "rikrak69@gmail.com",
    phone: "8837004917",
    entity: "Sole Proprietor",
    stage: "Early revenue",
    employment: "5",
    livesImpacted: "20",
    turnover: "₹3.12 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Creates job opportunities for local residents while promoting eco-tourism, preserves natural beauty, supports economic growth, and encourages responsible travel that benefits both people and the environment.",
    products: "Hospitality services, Farming products",
    externalLink: "https://www.primemeghalaya.com/bandasal-rural-resort/",
  },
  {
    slug: "ong-chnae-ktoi",
    businessName: "Ong chnae ktoi",
    entrepreneurName: "Paiaemdor LyngdohMawnai",
    district: "eastern-west-khasi-hills",
    sector: "handicrafts",
    image: "OngChnaeKtoicp.jpg",
    description: "Celebrates the rich handicraft traditions of Meghalaya, specializing in handmade creations like wall decor, frames, trophies, medals, notebooks, and personalized souvenirs — each blending traditional craftsmanship with modern design.",
    location: "Mairang, Eastern West Khasi Hills District",
    email: "laemdor@gmail.com",
    phone: "8729973107",
    entity: "Partnership",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹4.8 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Provides economic opportunities for artisans including persons with disabilities, supports local talent, promotes cultural pride, and contributes to community livelihoods while encouraging inclusivity and sustainable growth.",
    products: "Pebble art frames, Handmade wall décor, Personalized souvenirs, Custom trophies and medals",
    externalLink: "https://www.primemeghalaya.com/ong-chnae-ktoi/",
  },
  {
    slug: "mawrie-garments-manufacturer",
    businessName: "Mawrie Garments",
    entrepreneurName: "Fiyona Mawrie",
    district: "east-khasi-hills",
    sector: "textiles",
    image: "Mawriegarments5.jpg",
    description: "Specializes in fabric production and finished garments including school uniforms and institutional wear. Founded in 2020, targeting schools and security agencies as key market segments.",
    location: "Rynjah, Shillong, East Khasi Hills District",
    email: "Mawriegarmentsmanufacturer@gmail.com",
    phone: "7005021309",
    entity: "Partnership",
    stage: "Early revenue",
    employment: "13",
    livesImpacted: "52",
    turnover: "₹3.27 Lakh",
    govtFunding: "₹0.50 Lakh",
    socialImpact: "Supports local employment by producing quality fabric and finished products, playing a vital role in the local economy through an expanding market and product range.",
    products: "Ties, Socks, Skirts, Shirts, T-shirts, Lab coats, Pants, Scrubs",
    externalLink: "https://www.primemeghalaya.com/mawrie-garments-manufacturer/",
  },
  {
    slug: "ecommerce-buddy",
    businessName: "Ecommerce Buddy",
    entrepreneurName: "Sudip Kumar Das",
    district: "west-garo-hills",
    sector: "technology-it",
    image: "ecommercebuddylogo.jpg",
    description: "IT startup dedicated to supporting e-commerce sellers with tailored products and services designed to meet the specific needs of online businesses across India.",
    location: "Kasaripara, Hallydayganj, West Garo Hills District",
    email: "sudipkumardas43@gmail.com",
    phone: "9289201667",
    entity: "Sole Proprietor",
    stage: "In Revenue",
    employment: "5",
    livesImpacted: "20",
    turnover: "₹25.67 Lakh",
    govtFunding: "₹1 Lakh",
    socialImpact: "Empowers online businesses through tailored IT solutions that enhance efficiency and growth, contributing to the digital economy, promoting entrepreneurship, and creating employment in technology and retail sectors.",
    products: "E-Commerce solutions",
    externalLink: "https://www.primemeghalaya.com/ecommerce-buddy/",
  },
  {
    slug: "vox-crest-media",
    businessName: "Vox Crest Media",
    entrepreneurName: "Ferdinand Rani",
    district: "east-khasi-hills",
    sector: "technology-it",
    image: "voxcrestmediacp.jpg",
    description: "Combines storytelling with educational journalism and influencer marketing to expand brand reach and engagement through platforms including 4front Media, Ha Shillong Podcast, and Code Freemen.",
    location: "Lower Lachumiere, Shillong, East Khasi Hills District",
    email: "voxcrestmedia@gmail.com",
    phone: "8131943084",
    entity: "Partnership",
    stage: "Early revenue",
    employment: "14",
    livesImpacted: "56",
    turnover: "₹3.64 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Empowers communities through grassroots media literacy workshops and digital tool training while promoting cultural awareness and environmental consciousness through its platforms.",
    products: "Journalistic storytelling, Workshops & training, Media & PR consulting",
    externalLink: "https://www.primemeghalaya.com/vox-crest-media/",
  },
  {
    slug: "whispering-pines",
    businessName: "Whispering Pines",
    entrepreneurName: "Candida Kharsyntiew",
    district: "east-khasi-hills",
    sector: "food-processing",
    image: "whisperingpines.jpg",
    description: "Women's Self-Help Group passionate about food processing, preparing homemade pickles and juices, and offering packed lunch services from Mawlai-Mawroh, Shillong.",
    location: "Mawlai-Mawroh Umshing, East Khasi Hills District",
    phone: "9612168593",
    entity: "Self-Help Group",
    stage: "Early revenue",
    employment: "3",
    livesImpacted: "12",
    turnover: "₹0.72 Lakh",
    govtFunding: "₹11 Lakh",
    externalFunding: "₹18 Lakh",
    socialImpact: "Employs women from shelter homes, providing training and steady income, offering essential skills and financial independence to vulnerable women in the community.",
    products: "Chilli jam, Chilli oil, Chilli pickle, Lady's finger pickle, Bay Berry juice, Packed lunch services",
    externalLink: "https://www.primemeghalaya.com/whispering-pines/",
  },
  {
    slug: "marak-food-products",
    businessName: "Marak Food Products",
    entrepreneurName: "Tunila Ch. Marak",
    district: "east-garo-hills",
    sector: "food-processing",
    image: "Marakfoodproductscp.jpg",
    description: "Founded in 2019 to add value to locally sourced fruits, berries, and other regional produce from East Garo Hills. Pioneered the processing of oranges widely available in the region into premium jams and marmalades.",
    location: "Daribokgre, East Garo Hills",
    email: "ttunillachmarak@gmail.com",
    phone: "9362288648",
    employment: "14",
    livesImpacted: "56",
    turnover: "₹3.64 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "A force for social good — empowering farmers with reliable income, supporting local communities, and promoting sustainable and healthy food choices through locally sourced processing.",
    products: "Pineapple jam, Orange marmalade, Roselle jam, Roselle tea",
    externalLink: "https://www.primemeghalaya.com/marak-food-products/",
  },
  {
    slug: "jency-handicrafts",
    businessName: "Jency Handicrafts",
    entrepreneurName: "Jency Suchiang",
    district: "east-jaintia-hills",
    sector: "handicrafts",
    image: "Sharakritprofile.jpg",
    description: "Started in 2019, Jency Handicrafts specializes in bamboo and cane handicrafts including stools, baskets, jewelry, and home decor, with a focus on sustainability and traditional craftsmanship.",
    location: "Sohkymphor, East Jaintia Hills District",
    email: "jencysuchiang@gmail.com",
    phone: "9378178107",
    employment: "14",
    livesImpacted: "56",
    turnover: "₹3.64 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Focuses on sustainability using locally sourced bamboo and cane. Trains members of producer groups, self-help groups, and local youth, with particular emphasis on empowering women from neighboring areas.",
    products: "Bamboo & cane stools, Cane baskets, Cane jewelry, Home decor items",
    externalLink: "https://www.primemeghalaya.com/jency-handicrafts/",
  },
  {
    slug: "sharak-rit",
    businessName: "Sharak Rit",
    entrepreneurName: "Amstrong Shylla",
    district: "south-west-khasi-hills",
    sector: "food-processing",
    image: "Sharakritrlcp.jpg",
    description: "Makes organic King Chilli paste using homegrown ingredients from South West Khasi Hills, keeping flavors authentic and quality high through direct farm-to-jar processing.",
    location: "Mawbidong, South West Khasi Hills",
    email: "amstrongshylla@gmail.com",
    phone: "9366422610",
    employment: "14",
    livesImpacted: "56",
    turnover: "₹3.64 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Buys directly from farmers to help them earn better and keep traditional farming alive. Promotes organic methods, reducing chemical use and supporting a healthier way of farming in the region.",
    products: "King Chilli paste, Bamboo shoot pickle, Carrot pickle, Mushroom, Fruit jams (jackfruit, pineapple, mango), Juices (pineapple, mango, jackfruit)",
    externalLink: "https://www.primemeghalaya.com/sharak-rit",
  },
  {
    slug: "daka-handicraft",
    businessName: "Daka Handicraft",
    entrepreneurName: "Dakaeishwami Shadap",
    district: "east-jaintia-hills",
    sector: "handicrafts",
    image: "Dakahandicraft.jpg",
    description: "Specializes in handmade cane and bamboo products focusing on eco-friendly, sustainable handicrafts while training youth and empowering women in Kongthong village, East Jaintia Hills.",
    location: "Byrwai, East Jaintia Hills",
    email: "shadapdakaeishwami@gmail.com",
    phone: "9862269214",
    employment: "14",
    livesImpacted: "56",
    turnover: "₹3.64 Lakh",
    govtFunding: "₹2 Lakh",
    socialImpact: "Empowers women through employment and trains youth in Kongthong, offering skills and income opportunities post-training while promoting sustainability through local, eco-friendly materials.",
    products: "Baskets, Cane & bamboo jewelry, Home decor items",
    externalLink: "https://www.primemeghalaya.com/daka-handicraft",
  },
];

export function getProfile(slug: string): EntrepreneurProfile | undefined {
  return profiles.find((p) => p.slug === slug);
}
